# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.bid_offer_acceptances_api import BidOfferAcceptancesApi  # noqa: E501


class TestBidOfferAcceptancesApi(unittest.TestCase):
    """BidOfferAcceptancesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BidOfferAcceptancesApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_balancing_acceptances_all_get(self) -> None:
        """Test case for balancing_acceptances_all_get

        Bid Offer Acceptances Market-wide  # noqa: E501
        """
        pass

    def test_balancing_acceptances_get(self) -> None:
        """Test case for balancing_acceptances_get

        Bid Offer Acceptances Per-BMU  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
