# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.transparency_api import TransparencyApi  # noqa: E501


class TestTransparencyApi(unittest.TestCase):
    """TransparencyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransparencyApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_demand_total_actual_get(self) -> None:
        """Test case for demand_total_actual_get

        Actual Total Load Per Bidding Zone (ATL / B0610)  # noqa: E501
        """
        pass

    def test_forecast_demand_total_day_ahead_get(self) -> None:
        """Test case for forecast_demand_total_day_ahead_get

        Day-Ahead Total Load Forecast Per Bidding Zone (DATL / B0620)  # noqa: E501
        """
        pass

    def test_forecast_demand_total_week_ahead_get(self) -> None:
        """Test case for forecast_demand_total_week_ahead_get

        Week-Ahead Total Load Forecast Per Bidding Zone (WATL / B0630) filtered by forecast week  # noqa: E501
        """
        pass

    def test_forecast_demand_total_week_ahead_latest_get(self) -> None:
        """Test case for forecast_demand_total_week_ahead_latest_get

        Latest Week-Ahead Total Load Forecast Per Bidding Zone (WATL / B0630)  # noqa: E501
        """
        pass

    def test_forecast_generation_day_ahead_get(self) -> None:
        """Test case for forecast_generation_day_ahead_get

        Day-Ahead Aggregated Generation (DAG / B1430)  # noqa: E501
        """
        pass

    def test_forecast_generation_wind_and_solar_day_ahead_get(self) -> None:
        """Test case for forecast_generation_wind_and_solar_day_ahead_get

        Day-Ahead Generation forecasts For Wind And Solar (DGWS / B1440)  # noqa: E501
        """
        pass

    def test_generation_actual_per_type_day_total_get(self) -> None:
        """Test case for generation_actual_per_type_day_total_get

        24-hour Actual Generation Per Type (AGPT / B1620) summary data  # noqa: E501
        """
        pass

    def test_generation_actual_per_type_get(self) -> None:
        """Test case for generation_actual_per_type_get

        Actual Aggregated Generation Per Type (AGPT / B1620)  # noqa: E501
        """
        pass

    def test_generation_actual_per_type_wind_and_solar_get(self) -> None:
        """Test case for generation_actual_per_type_wind_and_solar_get

        Actual Or Estimated Wind And Solar Power Generation (AGWS / B1630)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
