# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.availability_api import AvailabilityApi  # noqa: E501


class TestAvailabilityApi(unittest.TestCase):
    """AvailabilityApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AvailabilityApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_generation_availability_summary14_d_get(self) -> None:
        """Test case for generation_availability_summary14_d_get

        Fourteen-day generation forecast  # noqa: E501
        """
        pass

    def test_generation_availability_summary3_yw_get(self) -> None:
        """Test case for generation_availability_summary3_yw_get

        Three-year generation forecast  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
