# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.insights_api_models_responses_balancing_disaggregated_balancing_services_adjustment_details_response import InsightsApiModelsResponsesBalancingDisaggregatedBalancingServicesAdjustmentDetailsResponse  # noqa: E501

class TestInsightsApiModelsResponsesBalancingDisaggregatedBalancingServicesAdjustmentDetailsResponse(unittest.TestCase):
    """InsightsApiModelsResponsesBalancingDisaggregatedBalancingServicesAdjustmentDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InsightsApiModelsResponsesBalancingDisaggregatedBalancingServicesAdjustmentDetailsResponse:
        """Test InsightsApiModelsResponsesBalancingDisaggregatedBalancingServicesAdjustmentDetailsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InsightsApiModelsResponsesBalancingDisaggregatedBalancingServicesAdjustmentDetailsResponse`
        """
        model = InsightsApiModelsResponsesBalancingDisaggregatedBalancingServicesAdjustmentDetailsResponse()  # noqa: E501
        if include_optional:
            return InsightsApiModelsResponsesBalancingDisaggregatedBalancingServicesAdjustmentDetailsResponse(
                settlement_date = 'Sat Jun 25 02:00:00 CEST 2022',
                settlement_period = 29,
                start_time = '2022-06-25T13:00Z',
                id = 1,
                cost = 1850.9,
                volume = 5,
                price = 370.18,
                so_flag = True,
                stor_flag = True,
                party_id = 'ElectroRoute Energy Trading Limited',
                asset_id = 'ING-ELTR1',
                is_tendered = True,
                service = 'Energy'
            )
        else:
            return InsightsApiModelsResponsesBalancingDisaggregatedBalancingServicesAdjustmentDetailsResponse(
        )
        """

    def testInsightsApiModelsResponsesBalancingDisaggregatedBalancingServicesAdjustmentDetailsResponse(self):
        """Test InsightsApiModelsResponsesBalancingDisaggregatedBalancingServicesAdjustmentDetailsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
