# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.wind_generation_forecast_api import WindGenerationForecastApi  # noqa: E501


class TestWindGenerationForecastApi(unittest.TestCase):
    """WindGenerationForecastApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WindGenerationForecastApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_forecast_generation_wind_earliest_get(self) -> None:
        """Test case for forecast_generation_wind_earliest_get

        Earliest wind generation forecast  # noqa: E501
        """
        pass

    def test_forecast_generation_wind_earliest_stream_get(self) -> None:
        """Test case for forecast_generation_wind_earliest_stream_get

        Earliest wind generation forecast stream  # noqa: E501
        """
        pass

    def test_forecast_generation_wind_evolution_get(self) -> None:
        """Test case for forecast_generation_wind_evolution_get

        Evolution wind generation forecast  # noqa: E501
        """
        pass

    def test_forecast_generation_wind_get(self) -> None:
        """Test case for forecast_generation_wind_get

        Latest wind generation forecast  # noqa: E501
        """
        pass

    def test_forecast_generation_wind_history_get(self) -> None:
        """Test case for forecast_generation_wind_history_get

        Historical wind generation forecast  # noqa: E501
        """
        pass

    def test_forecast_generation_wind_latest_get(self) -> None:
        """Test case for forecast_generation_wind_latest_get

        Latest wind generation forecast  # noqa: E501
        """
        pass

    def test_forecast_generation_wind_latest_stream_get(self) -> None:
        """Test case for forecast_generation_wind_latest_stream_get

        Latest wind generation forecast stream  # noqa: E501
        """
        pass

    def test_forecast_generation_wind_peak_get(self) -> None:
        """Test case for forecast_generation_wind_peak_get

        Peak wind generation forecast  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
