# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.market_index_api import MarketIndexApi  # noqa: E501


class TestMarketIndexApi(unittest.TestCase):
    """MarketIndexApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarketIndexApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_balancing_pricing_market_index_get(self) -> None:
        """Test case for balancing_pricing_market_index_get

        Market Index Data (MID) price time series  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
