# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.total_demand_forecast_api import TotalDemandForecastApi  # noqa: E501


class TestTotalDemandForecastApi(unittest.TestCase):
    """TotalDemandForecastApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TotalDemandForecastApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_forecast_demand_total_day_ahead_get(self) -> None:
        """Test case for forecast_demand_total_day_ahead_get

        Day-Ahead Total Load Forecast Per Bidding Zone (DATL / B0620)  # noqa: E501
        """
        pass

    def test_forecast_demand_total_week_ahead_get(self) -> None:
        """Test case for forecast_demand_total_week_ahead_get

        Week-Ahead Total Load Forecast Per Bidding Zone (WATL / B0630) filtered by forecast week  # noqa: E501
        """
        pass

    def test_forecast_demand_total_week_ahead_latest_get(self) -> None:
        """Test case for forecast_demand_total_week_ahead_latest_get

        Latest Week-Ahead Total Load Forecast Per Bidding Zone (WATL / B0630)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
