# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.insights_api_models_responses_reference_interconnector_data import InsightsApiModelsResponsesReferenceInterconnectorData  # noqa: E501

class TestInsightsApiModelsResponsesReferenceInterconnectorData(unittest.TestCase):
    """InsightsApiModelsResponsesReferenceInterconnectorData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InsightsApiModelsResponsesReferenceInterconnectorData:
        """Test InsightsApiModelsResponsesReferenceInterconnectorData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InsightsApiModelsResponsesReferenceInterconnectorData`
        """
        model = InsightsApiModelsResponsesReferenceInterconnectorData()  # noqa: E501
        if include_optional:
            return InsightsApiModelsResponsesReferenceInterconnectorData(
                interconnector_id = '',
                interconnector_name = '',
                interconnector_bidding_zone = ''
            )
        else:
            return InsightsApiModelsResponsesReferenceInterconnectorData(
        )
        """

    def testInsightsApiModelsResponsesReferenceInterconnectorData(self):
        """Test InsightsApiModelsResponsesReferenceInterconnectorData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
