# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.non_bmstor_api import NonBMSTORApi  # noqa: E501


class TestNonBMSTORApi(unittest.TestCase):
    """NonBMSTORApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NonBMSTORApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_balancing_nonbm_stor_events_get(self) -> None:
        """Test case for balancing_nonbm_stor_events_get

        Non-BM STOR (NONBM) events  # noqa: E501
        """
        pass

    def test_balancing_nonbm_stor_get(self) -> None:
        """Test case for balancing_nonbm_stor_get

        Non-BM STOR (NONBM) time series  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
