# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.insights_api_models_responses_transparency_actual_generation_by_settlement_period import InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod  # noqa: E501

class TestInsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod(unittest.TestCase):
    """InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod:
        """Test InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod`
        """
        model = InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod()  # noqa: E501
        if include_optional:
            return InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod(
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                settlement_period = 16,
                data = [
                    openapi_client.models.insights/api/models/responses/transparency/actual_generation_value.Insights.Api.Models.Responses.Transparency.ActualGenerationValue(
                        business_type = 'Solar generation', 
                        psr_type = 'Solar', 
                        quantity = 1829, )
                    ]
            )
        else:
            return InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod(
        )
        """

    def testInsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod(self):
        """Test InsightsApiModelsResponsesTransparencyActualGenerationBySettlementPeriod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
