# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.demand_control_instructions_api import DemandControlInstructionsApi  # noqa: E501


class TestDemandControlInstructionsApi(unittest.TestCase):
    """DemandControlInstructionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DemandControlInstructionsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_system_demand_control_instructions_get(self) -> None:
        """Test case for system_demand_control_instructions_get

        Demand Control Instruction (DCI)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
