# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.generation_forecast_api import GenerationForecastApi  # noqa: E501


class TestGenerationForecastApi(unittest.TestCase):
    """GenerationForecastApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GenerationForecastApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_forecast_generation_day_ahead_get(self) -> None:
        """Test case for forecast_generation_day_ahead_get

        Day-Ahead Aggregated Generation (DAG / B1430)  # noqa: E501
        """
        pass

    def test_forecast_generation_wind_and_solar_day_ahead_get(self) -> None:
        """Test case for forecast_generation_wind_and_solar_day_ahead_get

        Day-Ahead Generation forecasts For Wind And Solar (DGWS / B1440)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
