# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.insights_api_models_responses_transparency_day_ahead_generation_for_wind_and_solar import InsightsApiModelsResponsesTransparencyDayAheadGenerationForWindAndSolar  # noqa: E501

class TestInsightsApiModelsResponsesTransparencyDayAheadGenerationForWindAndSolar(unittest.TestCase):
    """InsightsApiModelsResponsesTransparencyDayAheadGenerationForWindAndSolar unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InsightsApiModelsResponsesTransparencyDayAheadGenerationForWindAndSolar:
        """Test InsightsApiModelsResponsesTransparencyDayAheadGenerationForWindAndSolar
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InsightsApiModelsResponsesTransparencyDayAheadGenerationForWindAndSolar`
        """
        model = InsightsApiModelsResponsesTransparencyDayAheadGenerationForWindAndSolar()  # noqa: E501
        if include_optional:
            return InsightsApiModelsResponsesTransparencyDayAheadGenerationForWindAndSolar(
                publish_time = '2023-06-29T17:25:09Z',
                process_type = 'Intraday process',
                business_type = 'Wind generation',
                psr_type = 'Wind Offshore',
                start_time = '2023-06-29T15:30Z',
                settlement_date = 'Thu Jun 29 02:00:00 CEST 2023',
                settlement_period = 40,
                quantity = 1000
            )
        else:
            return InsightsApiModelsResponsesTransparencyDayAheadGenerationForWindAndSolar(
        )
        """

    def testInsightsApiModelsResponsesTransparencyDayAheadGenerationForWindAndSolar(self):
        """Test InsightsApiModelsResponsesTransparencyDayAheadGenerationForWindAndSolar"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
