# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.margin_forecast_api import MarginForecastApi  # noqa: E501


class TestMarginForecastApi(unittest.TestCase):
    """MarginForecastApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarginForecastApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_forecast_margin_daily_evolution_get(self) -> None:
        """Test case for forecast_margin_daily_evolution_get

        Evolution Daily Margin Forecast  # noqa: E501
        """
        pass

    def test_forecast_margin_daily_get(self) -> None:
        """Test case for forecast_margin_daily_get

        Daily Margin Forecast  # noqa: E501
        """
        pass

    def test_forecast_margin_daily_history_get(self) -> None:
        """Test case for forecast_margin_daily_history_get

        Historical Daily Margin Forecast  # noqa: E501
        """
        pass

    def test_forecast_margin_weekly_evolution_get(self) -> None:
        """Test case for forecast_margin_weekly_evolution_get

        Evolution Daily Margin Forecast  # noqa: E501
        """
        pass

    def test_forecast_margin_weekly_get(self) -> None:
        """Test case for forecast_margin_weekly_get

        Weekly Margin Forecast  # noqa: E501
        """
        pass

    def test_forecast_margin_weekly_history_get(self) -> None:
        """Test case for forecast_margin_weekly_history_get

        Historical Weekly Margin Forecast  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
