# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.insights_api_models_responses_generation_forecast_fuel_data import InsightsApiModelsResponsesGenerationForecastFuelData  # noqa: E501

class TestInsightsApiModelsResponsesGenerationForecastFuelData(unittest.TestCase):
    """InsightsApiModelsResponsesGenerationForecastFuelData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InsightsApiModelsResponsesGenerationForecastFuelData:
        """Test InsightsApiModelsResponsesGenerationForecastFuelData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InsightsApiModelsResponsesGenerationForecastFuelData`
        """
        model = InsightsApiModelsResponsesGenerationForecastFuelData()  # noqa: E501
        if include_optional:
            return InsightsApiModelsResponsesGenerationForecastFuelData(
                fuel_type = '',
                output_usable = 56
            )
        else:
            return InsightsApiModelsResponsesGenerationForecastFuelData(
        )
        """

    def testInsightsApiModelsResponsesGenerationForecastFuelData(self):
        """Test InsightsApiModelsResponsesGenerationForecastFuelData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
