# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.insights_api_models_responses_balancing_credit_default_notice_response import InsightsApiModelsResponsesBalancingCreditDefaultNoticeResponse  # noqa: E501

class TestInsightsApiModelsResponsesBalancingCreditDefaultNoticeResponse(unittest.TestCase):
    """InsightsApiModelsResponsesBalancingCreditDefaultNoticeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InsightsApiModelsResponsesBalancingCreditDefaultNoticeResponse:
        """Test InsightsApiModelsResponsesBalancingCreditDefaultNoticeResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InsightsApiModelsResponsesBalancingCreditDefaultNoticeResponse`
        """
        model = InsightsApiModelsResponsesBalancingCreditDefaultNoticeResponse()  # noqa: E501
        if include_optional:
            return InsightsApiModelsResponsesBalancingCreditDefaultNoticeResponse(
                participant_id = 'INVE',
                participant_name = 'AMPowerUK Ltd',
                credit_default_level = 2,
                entered_default_settlement_date = 'Sat Jun 25 02:00:00 CEST 2022',
                entered_default_settlement_period = 3,
                cleared_default_settlement_date = 'Sat Jul 02 02:00:00 CEST 2022',
                cleared_default_settlement_period = 29,
                cleared_default_text = 'Credit Cover Percentage greater than or equal to 90% of Credit Limit (Level 2 Default)'
            )
        else:
            return InsightsApiModelsResponsesBalancingCreditDefaultNoticeResponse(
        )
        """

    def testInsightsApiModelsResponsesBalancingCreditDefaultNoticeResponse(self):
        """Test InsightsApiModelsResponsesBalancingCreditDefaultNoticeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
