# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.insights_api_models_responses_misc_system_warnings_data import InsightsApiModelsResponsesMiscSystemWarningsData  # noqa: E501

class TestInsightsApiModelsResponsesMiscSystemWarningsData(unittest.TestCase):
    """InsightsApiModelsResponsesMiscSystemWarningsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InsightsApiModelsResponsesMiscSystemWarningsData:
        """Test InsightsApiModelsResponsesMiscSystemWarningsData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InsightsApiModelsResponsesMiscSystemWarningsData`
        """
        model = InsightsApiModelsResponsesMiscSystemWarningsData()  # noqa: E501
        if include_optional:
            return InsightsApiModelsResponsesMiscSystemWarningsData(
                publish_time = '2022-09-20T00:00Z',
                warning_type = 'IT SYSTEMS OUTAGE',
                warning_text = 'NATIONAL GRID NOTIFICATION of excess energy prices used for settlement outside of BALIT for SO to SO Transactions'
            )
        else:
            return InsightsApiModelsResponsesMiscSystemWarningsData(
        )
        """

    def testInsightsApiModelsResponsesMiscSystemWarningsData(self):
        """Test InsightsApiModelsResponsesMiscSystemWarningsData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
