# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.insights_api_models_responses_balancing_settlement_settlement_message_response import InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse  # noqa: E501

class TestInsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse(unittest.TestCase):
    """InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse:
        """Test InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse`
        """
        model = InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse()  # noqa: E501
        if include_optional:
            return InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse(
                settlement_date = 'Mon Sep 18 02:00:00 CEST 2023',
                settlement_period = 2,
                message_received_date_time = '2023-09-17T15:31:12Z',
                message_severity = 'Error',
                message_type = 'FPN',
                message_text = 'No FPN files have been received.'
            )
        else:
            return InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse(
        )
        """

    def testInsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse(self):
        """Test InsightsApiModelsResponsesBalancingSettlementSettlementMessageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
