# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.demand_forecast_api import DemandForecastApi  # noqa: E501


class TestDemandForecastApi(unittest.TestCase):
    """DemandForecastApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DemandForecastApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_forecast_demand_daily_evolution_get(self) -> None:
        """Test case for forecast_demand_daily_evolution_get

        Evolution Daily Demand Forecast  # noqa: E501
        """
        pass

    def test_forecast_demand_daily_get(self) -> None:
        """Test case for forecast_demand_daily_get

        Fourteen day forecast demand  # noqa: E501
        """
        pass

    def test_forecast_demand_daily_history_get(self) -> None:
        """Test case for forecast_demand_daily_history_get

        Historical daily forecast demand  # noqa: E501
        """
        pass

    def test_forecast_demand_day_ahead_earliest_get(self) -> None:
        """Test case for forecast_demand_day_ahead_earliest_get

        Earliest published day-ahead demand forecast data for a given settlement period  # noqa: E501
        """
        pass

    def test_forecast_demand_day_ahead_earliest_stream_get(self) -> None:
        """Test case for forecast_demand_day_ahead_earliest_stream_get

        Stream of earliest day-ahead demand forecast data for a given settlement period  # noqa: E501
        """
        pass

    def test_forecast_demand_day_ahead_evolution_get(self) -> None:
        """Test case for forecast_demand_day_ahead_evolution_get

        Evolution Day-ahead Demand forecast  # noqa: E501
        """
        pass

    def test_forecast_demand_day_ahead_get(self) -> None:
        """Test case for forecast_demand_day_ahead_get

        Day-ahead demand forecast  # noqa: E501
        """
        pass

    def test_forecast_demand_day_ahead_history_get(self) -> None:
        """Test case for forecast_demand_day_ahead_history_get

        Historical day-ahead forecast demand  # noqa: E501
        """
        pass

    def test_forecast_demand_day_ahead_latest_get(self) -> None:
        """Test case for forecast_demand_day_ahead_latest_get

        Latest published day-ahead demand forecast data for a given settlement period  # noqa: E501
        """
        pass

    def test_forecast_demand_day_ahead_latest_stream_get(self) -> None:
        """Test case for forecast_demand_day_ahead_latest_stream_get

        Stream of latest published day-ahead demand forecast data for a given settlement period  # noqa: E501
        """
        pass

    def test_forecast_demand_day_ahead_peak_get(self) -> None:
        """Test case for forecast_demand_day_ahead_peak_get

        Retrieve peak demand data for each day, based on Day Ahead forecast data  # noqa: E501
        """
        pass

    def test_forecast_demand_weekly_evolution_get(self) -> None:
        """Test case for forecast_demand_weekly_evolution_get

        Evolution Weekly Demand Forecast  # noqa: E501
        """
        pass

    def test_forecast_demand_weekly_get(self) -> None:
        """Test case for forecast_demand_weekly_get

        Weekly forecast demand  # noqa: E501
        """
        pass

    def test_forecast_demand_weekly_history_get(self) -> None:
        """Test case for forecast_demand_weekly_history_get

        Historical weekly forecast demand  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
