# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.system_frequency_api import SystemFrequencyApi  # noqa: E501


class TestSystemFrequencyApi(unittest.TestCase):
    """SystemFrequencyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SystemFrequencyApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_system_frequency_get(self) -> None:
        """Test case for system_frequency_get

        System Frequency  # noqa: E501
        """
        pass

    def test_system_frequency_stream_get(self) -> None:
        """Test case for system_frequency_stream_get

        System Frequency Stream  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
