# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.insights_api_models_responses_reference_bm_unit_data import InsightsApiModelsResponsesReferenceBmUnitData  # noqa: E501

class TestInsightsApiModelsResponsesReferenceBmUnitData(unittest.TestCase):
    """InsightsApiModelsResponsesReferenceBmUnitData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InsightsApiModelsResponsesReferenceBmUnitData:
        """Test InsightsApiModelsResponsesReferenceBmUnitData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InsightsApiModelsResponsesReferenceBmUnitData`
        """
        model = InsightsApiModelsResponsesReferenceBmUnitData()  # noqa: E501
        if include_optional:
            return InsightsApiModelsResponsesReferenceBmUnitData(
                national_grid_bm_unit = '',
                elexon_bm_unit = '',
                fuel_type = '',
                lead_party_name = '',
                bm_unit_type = '',
                fpn_flag = True
            )
        else:
            return InsightsApiModelsResponsesReferenceBmUnitData(
        )
        """

    def testInsightsApiModelsResponsesReferenceBmUnitData(self):
        """Test InsightsApiModelsResponsesReferenceBmUnitData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
