# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class InsightsApiModelsResponsesReferenceInterconnectorData(BaseModel):
    """
    InsightsApiModelsResponsesReferenceInterconnectorData
    """
    interconnector_id: Optional[StrictStr] = Field(None, alias="interconnectorId")
    interconnector_name: Optional[StrictStr] = Field(None, alias="interconnectorName")
    interconnector_bidding_zone: Optional[StrictStr] = Field(None, alias="interconnectorBiddingZone")
    __properties = ["interconnectorId", "interconnectorName", "interconnectorBiddingZone"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InsightsApiModelsResponsesReferenceInterconnectorData:
        """Create an instance of InsightsApiModelsResponsesReferenceInterconnectorData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if interconnector_id (nullable) is None
        # and __fields_set__ contains the field
        if self.interconnector_id is None and "interconnector_id" in self.__fields_set__:
            _dict['interconnectorId'] = None

        # set to None if interconnector_name (nullable) is None
        # and __fields_set__ contains the field
        if self.interconnector_name is None and "interconnector_name" in self.__fields_set__:
            _dict['interconnectorName'] = None

        # set to None if interconnector_bidding_zone (nullable) is None
        # and __fields_set__ contains the field
        if self.interconnector_bidding_zone is None and "interconnector_bidding_zone" in self.__fields_set__:
            _dict['interconnectorBiddingZone'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InsightsApiModelsResponsesReferenceInterconnectorData:
        """Create an instance of InsightsApiModelsResponsesReferenceInterconnectorData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InsightsApiModelsResponsesReferenceInterconnectorData.parse_obj(obj)

        _obj = InsightsApiModelsResponsesReferenceInterconnectorData.parse_obj({
            "interconnector_id": obj.get("interconnectorId"),
            "interconnector_name": obj.get("interconnectorName"),
            "interconnector_bidding_zone": obj.get("interconnectorBiddingZone")
        })
        return _obj


