# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt

class InsightsApiModelsResponsesTransparencyDayAheadTotalLoadPerBiddingZone(BaseModel):
    """
    InsightsApiModelsResponsesTransparencyDayAheadTotalLoadPerBiddingZone
    """
    publish_time: Optional[datetime] = Field(None, alias="publishTime")
    start_time: Optional[datetime] = Field(None, alias="startTime")
    settlement_date: Optional[date] = Field(None, alias="settlementDate")
    settlement_period: Optional[StrictInt] = Field(None, alias="settlementPeriod")
    quantity: Optional[Union[StrictFloat, StrictInt]] = None
    __properties = ["publishTime", "startTime", "settlementDate", "settlementPeriod", "quantity"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InsightsApiModelsResponsesTransparencyDayAheadTotalLoadPerBiddingZone:
        """Create an instance of InsightsApiModelsResponsesTransparencyDayAheadTotalLoadPerBiddingZone from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InsightsApiModelsResponsesTransparencyDayAheadTotalLoadPerBiddingZone:
        """Create an instance of InsightsApiModelsResponsesTransparencyDayAheadTotalLoadPerBiddingZone from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InsightsApiModelsResponsesTransparencyDayAheadTotalLoadPerBiddingZone.parse_obj(obj)

        _obj = InsightsApiModelsResponsesTransparencyDayAheadTotalLoadPerBiddingZone.parse_obj({
            "publish_time": obj.get("publishTime"),
            "start_time": obj.get("startTime"),
            "settlement_date": obj.get("settlementDate"),
            "settlement_period": obj.get("settlementPeriod"),
            "quantity": obj.get("quantity")
        })
        return _obj


