# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr

class InsightsApiModelsResponsesBalancingDynamicRateData(BaseModel):
    """
    InsightsApiModelsResponsesBalancingDynamicRateData
    """
    dataset: Optional[StrictStr] = None
    settlement_date: Optional[date] = Field(None, alias="settlementDate")
    settlement_period: Optional[StrictInt] = Field(None, alias="settlementPeriod")
    time: Optional[datetime] = None
    rate1: Optional[Union[StrictFloat, StrictInt]] = None
    elbow2: Optional[Union[StrictFloat, StrictInt]] = None
    rate2: Optional[Union[StrictFloat, StrictInt]] = None
    elbow3: Optional[Union[StrictFloat, StrictInt]] = None
    rate3: Optional[Union[StrictFloat, StrictInt]] = None
    national_grid_bm_unit: Optional[StrictStr] = Field(None, alias="nationalGridBmUnit")
    bm_unit: Optional[StrictStr] = Field(None, alias="bmUnit")
    __properties = ["dataset", "settlementDate", "settlementPeriod", "time", "rate1", "elbow2", "rate2", "elbow3", "rate3", "nationalGridBmUnit", "bmUnit"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InsightsApiModelsResponsesBalancingDynamicRateData:
        """Create an instance of InsightsApiModelsResponsesBalancingDynamicRateData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if dataset (nullable) is None
        # and __fields_set__ contains the field
        if self.dataset is None and "dataset" in self.__fields_set__:
            _dict['dataset'] = None

        # set to None if elbow2 (nullable) is None
        # and __fields_set__ contains the field
        if self.elbow2 is None and "elbow2" in self.__fields_set__:
            _dict['elbow2'] = None

        # set to None if rate2 (nullable) is None
        # and __fields_set__ contains the field
        if self.rate2 is None and "rate2" in self.__fields_set__:
            _dict['rate2'] = None

        # set to None if elbow3 (nullable) is None
        # and __fields_set__ contains the field
        if self.elbow3 is None and "elbow3" in self.__fields_set__:
            _dict['elbow3'] = None

        # set to None if rate3 (nullable) is None
        # and __fields_set__ contains the field
        if self.rate3 is None and "rate3" in self.__fields_set__:
            _dict['rate3'] = None

        # set to None if national_grid_bm_unit (nullable) is None
        # and __fields_set__ contains the field
        if self.national_grid_bm_unit is None and "national_grid_bm_unit" in self.__fields_set__:
            _dict['nationalGridBmUnit'] = None

        # set to None if bm_unit (nullable) is None
        # and __fields_set__ contains the field
        if self.bm_unit is None and "bm_unit" in self.__fields_set__:
            _dict['bmUnit'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InsightsApiModelsResponsesBalancingDynamicRateData:
        """Create an instance of InsightsApiModelsResponsesBalancingDynamicRateData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InsightsApiModelsResponsesBalancingDynamicRateData.parse_obj(obj)

        _obj = InsightsApiModelsResponsesBalancingDynamicRateData.parse_obj({
            "dataset": obj.get("dataset"),
            "settlement_date": obj.get("settlementDate"),
            "settlement_period": obj.get("settlementPeriod"),
            "time": obj.get("time"),
            "rate1": obj.get("rate1"),
            "elbow2": obj.get("elbow2"),
            "rate2": obj.get("rate2"),
            "elbow3": obj.get("elbow3"),
            "rate3": obj.get("rate3"),
            "national_grid_bm_unit": obj.get("nationalGridBmUnit"),
            "bm_unit": obj.get("bmUnit")
        })
        return _obj


