# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class InsightsApiModelsResponsesGenerationForecastFuelData(BaseModel):
    """
    InsightsApiModelsResponsesGenerationForecastFuelData
    """
    fuel_type: Optional[StrictStr] = Field(None, alias="fuelType")
    output_usable: Optional[StrictInt] = Field(None, alias="outputUsable")
    __properties = ["fuelType", "outputUsable"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InsightsApiModelsResponsesGenerationForecastFuelData:
        """Create an instance of InsightsApiModelsResponsesGenerationForecastFuelData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if fuel_type (nullable) is None
        # and __fields_set__ contains the field
        if self.fuel_type is None and "fuel_type" in self.__fields_set__:
            _dict['fuelType'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InsightsApiModelsResponsesGenerationForecastFuelData:
        """Create an instance of InsightsApiModelsResponsesGenerationForecastFuelData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InsightsApiModelsResponsesGenerationForecastFuelData.parse_obj(obj)

        _obj = InsightsApiModelsResponsesGenerationForecastFuelData.parse_obj({
            "fuel_type": obj.get("fuelType"),
            "output_usable": obj.get("outputUsable")
        })
        return _obj


