# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictInt

class InsightsApiModelsResponsesForecastSurplusForecastSurplusWeekly(BaseModel):
    """
    InsightsApiModelsResponsesForecastSurplusForecastSurplusWeekly
    """
    publish_time: Optional[datetime] = Field(None, alias="publishTime")
    surplus: Optional[StrictInt] = None
    week: Optional[StrictInt] = None
    year: Optional[StrictInt] = None
    week_start_date: Optional[date] = Field(None, alias="weekStartDate")
    __properties = ["publishTime", "surplus", "week", "year", "weekStartDate"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InsightsApiModelsResponsesForecastSurplusForecastSurplusWeekly:
        """Create an instance of InsightsApiModelsResponsesForecastSurplusForecastSurplusWeekly from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if surplus (nullable) is None
        # and __fields_set__ contains the field
        if self.surplus is None and "surplus" in self.__fields_set__:
            _dict['surplus'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InsightsApiModelsResponsesForecastSurplusForecastSurplusWeekly:
        """Create an instance of InsightsApiModelsResponsesForecastSurplusForecastSurplusWeekly from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InsightsApiModelsResponsesForecastSurplusForecastSurplusWeekly.parse_obj(obj)

        _obj = InsightsApiModelsResponsesForecastSurplusForecastSurplusWeekly.parse_obj({
            "publish_time": obj.get("publishTime"),
            "surplus": obj.get("surplus"),
            "week": obj.get("week"),
            "year": obj.get("year"),
            "week_start_date": obj.get("weekStartDate")
        })
        return _obj


