# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError

from typing_extensions import Annotated
from datetime import date, datetime

from pydantic import Field, StrictInt, StrictStr, conlist

from typing import Optional

from openapi_client.models.insights_api_models_responses_response_with_metadata1_insights_api_models_responses_generation_availability_daily import InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityDaily
from openapi_client.models.insights_api_models_responses_response_with_metadata1_insights_api_models_responses_generation_availability_weekly import InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityWeekly

from openapi_client.api_client import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class AvailabilityForecastApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def forecast_availability_daily_evolution_get(self, forecast_date : Annotated[date, Field(..., description="The forecast date for the filter. This must be in the format yyyy-MM-dd.")], level : Optional[StrictStr] = None, bm_unit : Optional[conlist(StrictStr)] = None, fuel_type : Optional[conlist(StrictStr)] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityDaily:  # noqa: E501
        """Evolution Daily Generation Forecast  # noqa: E501

        This endpoint provides the evolution of all daily generation forecasts over time for a given Forecast Date.                Date parameter must be provided in the exact format yyyy-MM-dd.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.forecast_availability_daily_evolution_get(forecast_date, level, bm_unit, fuel_type, format, async_req=True)
        >>> result = thread.get()

        :param forecast_date: The forecast date for the filter. This must be in the format yyyy-MM-dd. (required)
        :type forecast_date: date
        :param level:
        :type level: str
        :param bm_unit:
        :type bm_unit: List[str]
        :param fuel_type:
        :type fuel_type: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityDaily
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the forecast_availability_daily_evolution_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.forecast_availability_daily_evolution_get_with_http_info(forecast_date, level, bm_unit, fuel_type, format, **kwargs)  # noqa: E501

    @validate_arguments
    def forecast_availability_daily_evolution_get_with_http_info(self, forecast_date : Annotated[date, Field(..., description="The forecast date for the filter. This must be in the format yyyy-MM-dd.")], level : Optional[StrictStr] = None, bm_unit : Optional[conlist(StrictStr)] = None, fuel_type : Optional[conlist(StrictStr)] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Evolution Daily Generation Forecast  # noqa: E501

        This endpoint provides the evolution of all daily generation forecasts over time for a given Forecast Date.                Date parameter must be provided in the exact format yyyy-MM-dd.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.forecast_availability_daily_evolution_get_with_http_info(forecast_date, level, bm_unit, fuel_type, format, async_req=True)
        >>> result = thread.get()

        :param forecast_date: The forecast date for the filter. This must be in the format yyyy-MM-dd. (required)
        :type forecast_date: date
        :param level:
        :type level: str
        :param bm_unit:
        :type bm_unit: List[str]
        :param fuel_type:
        :type fuel_type: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityDaily, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'forecast_date',
            'level',
            'bm_unit',
            'fuel_type',
            'format'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method forecast_availability_daily_evolution_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('forecast_date') is not None:  # noqa: E501
            if isinstance(_params['forecast_date'], date):
                _query_params.append(('forecastDate', _params['forecast_date'].strftime(self.api_client.configuration.date_format)))
            else:
                _query_params.append(('forecastDate', _params['forecast_date']))

        if _params.get('level') is not None:  # noqa: E501
            _query_params.append(('level', _params['level']))

        if _params.get('bm_unit') is not None:  # noqa: E501
            _query_params.append(('bmUnit', _params['bm_unit']))
            _collection_formats['bmUnit'] = 'multi'

        if _params.get('fuel_type') is not None:  # noqa: E501
            _query_params.append(('fuelType', _params['fuel_type']))
            _collection_formats['fuelType'] = 'multi'

        if _params.get('format') is not None:  # noqa: E501
            _query_params.append(('format', _params['format']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json', 'application/xml', 'text/xml', 'text/csv'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityDaily",
        }

        return self.api_client.call_api(
            '/forecast/availability/daily/evolution', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def forecast_availability_daily_get(self, level : Optional[StrictStr] = None, bm_unit : Optional[conlist(StrictStr)] = None, fuel_type : Optional[conlist(StrictStr)] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityDaily:  # noqa: E501
        """Fourteen-day generation forecast  # noqa: E501

        This endpoint provides the latest fourteen-day generation forecast  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.forecast_availability_daily_get(level, bm_unit, fuel_type, format, async_req=True)
        >>> result = thread.get()

        :param level:
        :type level: str
        :param bm_unit:
        :type bm_unit: List[str]
        :param fuel_type:
        :type fuel_type: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityDaily
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the forecast_availability_daily_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.forecast_availability_daily_get_with_http_info(level, bm_unit, fuel_type, format, **kwargs)  # noqa: E501

    @validate_arguments
    def forecast_availability_daily_get_with_http_info(self, level : Optional[StrictStr] = None, bm_unit : Optional[conlist(StrictStr)] = None, fuel_type : Optional[conlist(StrictStr)] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Fourteen-day generation forecast  # noqa: E501

        This endpoint provides the latest fourteen-day generation forecast  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.forecast_availability_daily_get_with_http_info(level, bm_unit, fuel_type, format, async_req=True)
        >>> result = thread.get()

        :param level:
        :type level: str
        :param bm_unit:
        :type bm_unit: List[str]
        :param fuel_type:
        :type fuel_type: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityDaily, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'level',
            'bm_unit',
            'fuel_type',
            'format'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method forecast_availability_daily_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('level') is not None:  # noqa: E501
            _query_params.append(('level', _params['level']))

        if _params.get('bm_unit') is not None:  # noqa: E501
            _query_params.append(('bmUnit', _params['bm_unit']))
            _collection_formats['bmUnit'] = 'multi'

        if _params.get('fuel_type') is not None:  # noqa: E501
            _query_params.append(('fuelType', _params['fuel_type']))
            _collection_formats['fuelType'] = 'multi'

        if _params.get('format') is not None:  # noqa: E501
            _query_params.append(('format', _params['format']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json', 'application/xml', 'text/xml', 'text/csv'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityDaily",
        }

        return self.api_client.call_api(
            '/forecast/availability/daily', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def forecast_availability_daily_history_get(self, publish_time : datetime, level : Optional[StrictStr] = None, bm_unit : Optional[conlist(StrictStr)] = None, fuel_type : Optional[conlist(StrictStr)] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityDaily:  # noqa: E501
        """Historic Fourteen-day generation forecast  # noqa: E501

        This endpoint provides the latest fourteen-day generation forecast from a given DateTime  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.forecast_availability_daily_history_get(publish_time, level, bm_unit, fuel_type, format, async_req=True)
        >>> result = thread.get()

        :param publish_time: (required)
        :type publish_time: datetime
        :param level:
        :type level: str
        :param bm_unit:
        :type bm_unit: List[str]
        :param fuel_type:
        :type fuel_type: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityDaily
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the forecast_availability_daily_history_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.forecast_availability_daily_history_get_with_http_info(publish_time, level, bm_unit, fuel_type, format, **kwargs)  # noqa: E501

    @validate_arguments
    def forecast_availability_daily_history_get_with_http_info(self, publish_time : datetime, level : Optional[StrictStr] = None, bm_unit : Optional[conlist(StrictStr)] = None, fuel_type : Optional[conlist(StrictStr)] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Historic Fourteen-day generation forecast  # noqa: E501

        This endpoint provides the latest fourteen-day generation forecast from a given DateTime  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.forecast_availability_daily_history_get_with_http_info(publish_time, level, bm_unit, fuel_type, format, async_req=True)
        >>> result = thread.get()

        :param publish_time: (required)
        :type publish_time: datetime
        :param level:
        :type level: str
        :param bm_unit:
        :type bm_unit: List[str]
        :param fuel_type:
        :type fuel_type: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityDaily, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'publish_time',
            'level',
            'bm_unit',
            'fuel_type',
            'format'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method forecast_availability_daily_history_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('publish_time') is not None:  # noqa: E501
            if isinstance(_params['publish_time'], datetime):
                _query_params.append(('publishTime', _params['publish_time'].strftime(self.api_client.configuration.datetime_format)))
            else:
                _query_params.append(('publishTime', _params['publish_time']))

        if _params.get('level') is not None:  # noqa: E501
            _query_params.append(('level', _params['level']))

        if _params.get('bm_unit') is not None:  # noqa: E501
            _query_params.append(('bmUnit', _params['bm_unit']))
            _collection_formats['bmUnit'] = 'multi'

        if _params.get('fuel_type') is not None:  # noqa: E501
            _query_params.append(('fuelType', _params['fuel_type']))
            _collection_formats['fuelType'] = 'multi'

        if _params.get('format') is not None:  # noqa: E501
            _query_params.append(('format', _params['format']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json', 'application/xml', 'text/xml', 'text/csv'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityDaily",
        }

        return self.api_client.call_api(
            '/forecast/availability/daily/history', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def forecast_availability_weekly_evolution_get(self, year : StrictInt, week : StrictInt, level : Optional[StrictStr] = None, bm_unit : Optional[conlist(StrictStr)] = None, fuel_type : Optional[conlist(StrictStr)] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityWeekly:  # noqa: E501
        """Weekly Generation Forecast  # noqa: E501

        This endpoint provides all weekly generation forecasts over time for a given Year and Week  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.forecast_availability_weekly_evolution_get(year, week, level, bm_unit, fuel_type, format, async_req=True)
        >>> result = thread.get()

        :param year: (required)
        :type year: int
        :param week: (required)
        :type week: int
        :param level:
        :type level: str
        :param bm_unit:
        :type bm_unit: List[str]
        :param fuel_type:
        :type fuel_type: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityWeekly
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the forecast_availability_weekly_evolution_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.forecast_availability_weekly_evolution_get_with_http_info(year, week, level, bm_unit, fuel_type, format, **kwargs)  # noqa: E501

    @validate_arguments
    def forecast_availability_weekly_evolution_get_with_http_info(self, year : StrictInt, week : StrictInt, level : Optional[StrictStr] = None, bm_unit : Optional[conlist(StrictStr)] = None, fuel_type : Optional[conlist(StrictStr)] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Weekly Generation Forecast  # noqa: E501

        This endpoint provides all weekly generation forecasts over time for a given Year and Week  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.forecast_availability_weekly_evolution_get_with_http_info(year, week, level, bm_unit, fuel_type, format, async_req=True)
        >>> result = thread.get()

        :param year: (required)
        :type year: int
        :param week: (required)
        :type week: int
        :param level:
        :type level: str
        :param bm_unit:
        :type bm_unit: List[str]
        :param fuel_type:
        :type fuel_type: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityWeekly, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'year',
            'week',
            'level',
            'bm_unit',
            'fuel_type',
            'format'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method forecast_availability_weekly_evolution_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('year') is not None:  # noqa: E501
            _query_params.append(('year', _params['year']))

        if _params.get('week') is not None:  # noqa: E501
            _query_params.append(('week', _params['week']))

        if _params.get('level') is not None:  # noqa: E501
            _query_params.append(('level', _params['level']))

        if _params.get('bm_unit') is not None:  # noqa: E501
            _query_params.append(('bmUnit', _params['bm_unit']))
            _collection_formats['bmUnit'] = 'multi'

        if _params.get('fuel_type') is not None:  # noqa: E501
            _query_params.append(('fuelType', _params['fuel_type']))
            _collection_formats['fuelType'] = 'multi'

        if _params.get('format') is not None:  # noqa: E501
            _query_params.append(('format', _params['format']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json', 'application/xml', 'text/xml', 'text/csv'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityWeekly",
        }

        return self.api_client.call_api(
            '/forecast/availability/weekly/evolution', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def forecast_availability_weekly_get(self, level : Optional[StrictStr] = None, bm_unit : Optional[conlist(StrictStr)] = None, fuel_type : Optional[conlist(StrictStr)] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityWeekly:  # noqa: E501
        """Weekly Generation Forecast  # noqa: E501

        This endpoint provides the latest three-year generation forecast  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.forecast_availability_weekly_get(level, bm_unit, fuel_type, format, async_req=True)
        >>> result = thread.get()

        :param level:
        :type level: str
        :param bm_unit:
        :type bm_unit: List[str]
        :param fuel_type:
        :type fuel_type: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityWeekly
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the forecast_availability_weekly_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.forecast_availability_weekly_get_with_http_info(level, bm_unit, fuel_type, format, **kwargs)  # noqa: E501

    @validate_arguments
    def forecast_availability_weekly_get_with_http_info(self, level : Optional[StrictStr] = None, bm_unit : Optional[conlist(StrictStr)] = None, fuel_type : Optional[conlist(StrictStr)] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Weekly Generation Forecast  # noqa: E501

        This endpoint provides the latest three-year generation forecast  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.forecast_availability_weekly_get_with_http_info(level, bm_unit, fuel_type, format, async_req=True)
        >>> result = thread.get()

        :param level:
        :type level: str
        :param bm_unit:
        :type bm_unit: List[str]
        :param fuel_type:
        :type fuel_type: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityWeekly, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'level',
            'bm_unit',
            'fuel_type',
            'format'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method forecast_availability_weekly_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('level') is not None:  # noqa: E501
            _query_params.append(('level', _params['level']))

        if _params.get('bm_unit') is not None:  # noqa: E501
            _query_params.append(('bmUnit', _params['bm_unit']))
            _collection_formats['bmUnit'] = 'multi'

        if _params.get('fuel_type') is not None:  # noqa: E501
            _query_params.append(('fuelType', _params['fuel_type']))
            _collection_formats['fuelType'] = 'multi'

        if _params.get('format') is not None:  # noqa: E501
            _query_params.append(('format', _params['format']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json', 'application/xml', 'text/xml', 'text/csv'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityWeekly",
        }

        return self.api_client.call_api(
            '/forecast/availability/weekly', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def forecast_availability_weekly_history_get(self, publish_time : datetime, level : Optional[StrictStr] = None, bm_unit : Optional[conlist(StrictStr)] = None, fuel_type : Optional[conlist(StrictStr)] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityWeekly:  # noqa: E501
        """Historic Weekly generation forecast  # noqa: E501

        This endpoint provides the latest three-year forecast from a given DateTime  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.forecast_availability_weekly_history_get(publish_time, level, bm_unit, fuel_type, format, async_req=True)
        >>> result = thread.get()

        :param publish_time: (required)
        :type publish_time: datetime
        :param level:
        :type level: str
        :param bm_unit:
        :type bm_unit: List[str]
        :param fuel_type:
        :type fuel_type: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityWeekly
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the forecast_availability_weekly_history_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.forecast_availability_weekly_history_get_with_http_info(publish_time, level, bm_unit, fuel_type, format, **kwargs)  # noqa: E501

    @validate_arguments
    def forecast_availability_weekly_history_get_with_http_info(self, publish_time : datetime, level : Optional[StrictStr] = None, bm_unit : Optional[conlist(StrictStr)] = None, fuel_type : Optional[conlist(StrictStr)] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Historic Weekly generation forecast  # noqa: E501

        This endpoint provides the latest three-year forecast from a given DateTime  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.forecast_availability_weekly_history_get_with_http_info(publish_time, level, bm_unit, fuel_type, format, async_req=True)
        >>> result = thread.get()

        :param publish_time: (required)
        :type publish_time: datetime
        :param level:
        :type level: str
        :param bm_unit:
        :type bm_unit: List[str]
        :param fuel_type:
        :type fuel_type: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityWeekly, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'publish_time',
            'level',
            'bm_unit',
            'fuel_type',
            'format'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method forecast_availability_weekly_history_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('publish_time') is not None:  # noqa: E501
            if isinstance(_params['publish_time'], datetime):
                _query_params.append(('publishTime', _params['publish_time'].strftime(self.api_client.configuration.datetime_format)))
            else:
                _query_params.append(('publishTime', _params['publish_time']))

        if _params.get('level') is not None:  # noqa: E501
            _query_params.append(('level', _params['level']))

        if _params.get('bm_unit') is not None:  # noqa: E501
            _query_params.append(('bmUnit', _params['bm_unit']))
            _collection_formats['bmUnit'] = 'multi'

        if _params.get('fuel_type') is not None:  # noqa: E501
            _query_params.append(('fuelType', _params['fuel_type']))
            _collection_formats['fuelType'] = 'multi'

        if _params.get('format') is not None:  # noqa: E501
            _query_params.append(('format', _params['format']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json', 'application/xml', 'text/xml', 'text/csv'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationAvailabilityWeekly",
        }

        return self.api_client.call_api(
            '/forecast/availability/weekly/history', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
