# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError

from typing_extensions import Annotated
from datetime import datetime

from pydantic import Field, StrictInt, StrictStr, conlist

from typing import Optional

from openapi_client.models.insights_api_models_responses_response_with_metadata1_insights_api_models_responses_balancing_dynamic_dynamic_data import InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicDynamicData
from openapi_client.models.insights_api_models_responses_response_with_metadata1_insights_api_models_responses_balancing_dynamic_rate_data import InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicRateData

from openapi_client.api_client import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class BalancingMechanismDynamicApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def balancing_dynamic_all_get(self, settlement_date : Annotated[datetime, Field(..., description="The settlement date or datetime to filter.")], settlement_period : Annotated[Optional[StrictInt], Field(description="The settlement period to filter. This should be an integer from 1-50 inclusive.")] = None, bm_unit : Annotated[Optional[conlist(StrictStr)], Field(description="The BM Units to query. Elexon or NGC BMU IDs can be used. If omitted, results for all BM units will be returned.")] = None, dataset : Annotated[Optional[conlist(StrictStr)], Field(description="Datasets to filter. If omitted, all datasets will be returned.")] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicDynamicData:  # noqa: E501
        """Dynamic Datasets Market-wide  # noqa: E501

        This endpoint provides the dynamic data for multiple requested BMUs or all BMUs, excluding dynamic rate data.  It returns the data valid for a single settlement period. This includes a snapshot of data valid at the start  of the settlement period, and any changes published during that settlement period.                By default, all of the relevant datasets are returned: SIL, SEL, NDZ, NTB, NTO, MZT, MNZT, MDV & MDP.  The results from each dataset are transformed to a common response model, with the common integer field *Value*  mapped from the fields *Level*, *Period*, *Volume* or *Notice* in the original dataset, as relevant.                The settlement period to query can be specified as a date and settlement period, or as a datetime  which will resolve to the settlement period that time falls within.    All Dates and DateTimes should be expressed as defined within  <a href=\"https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\" target=\"_blank\">RFC 3339</a>.    Some examples of date parameter combinations are shown below.                Filtering by datetime:                    /balancing/dynamic/all?settlementDate=2023-01-18T01:00Z                Filtering by settlement date and period:                    /balancing/dynamic/all?settlementDate=2023-01-18&settlementPeriod=3  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.balancing_dynamic_all_get(settlement_date, settlement_period, bm_unit, dataset, format, async_req=True)
        >>> result = thread.get()

        :param settlement_date: The settlement date or datetime to filter. (required)
        :type settlement_date: datetime
        :param settlement_period: The settlement period to filter. This should be an integer from 1-50 inclusive.
        :type settlement_period: int
        :param bm_unit: The BM Units to query. Elexon or NGC BMU IDs can be used. If omitted, results for all BM units will be returned.
        :type bm_unit: List[str]
        :param dataset: Datasets to filter. If omitted, all datasets will be returned.
        :type dataset: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicDynamicData
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the balancing_dynamic_all_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.balancing_dynamic_all_get_with_http_info(settlement_date, settlement_period, bm_unit, dataset, format, **kwargs)  # noqa: E501

    @validate_arguments
    def balancing_dynamic_all_get_with_http_info(self, settlement_date : Annotated[datetime, Field(..., description="The settlement date or datetime to filter.")], settlement_period : Annotated[Optional[StrictInt], Field(description="The settlement period to filter. This should be an integer from 1-50 inclusive.")] = None, bm_unit : Annotated[Optional[conlist(StrictStr)], Field(description="The BM Units to query. Elexon or NGC BMU IDs can be used. If omitted, results for all BM units will be returned.")] = None, dataset : Annotated[Optional[conlist(StrictStr)], Field(description="Datasets to filter. If omitted, all datasets will be returned.")] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Dynamic Datasets Market-wide  # noqa: E501

        This endpoint provides the dynamic data for multiple requested BMUs or all BMUs, excluding dynamic rate data.  It returns the data valid for a single settlement period. This includes a snapshot of data valid at the start  of the settlement period, and any changes published during that settlement period.                By default, all of the relevant datasets are returned: SIL, SEL, NDZ, NTB, NTO, MZT, MNZT, MDV & MDP.  The results from each dataset are transformed to a common response model, with the common integer field *Value*  mapped from the fields *Level*, *Period*, *Volume* or *Notice* in the original dataset, as relevant.                The settlement period to query can be specified as a date and settlement period, or as a datetime  which will resolve to the settlement period that time falls within.    All Dates and DateTimes should be expressed as defined within  <a href=\"https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\" target=\"_blank\">RFC 3339</a>.    Some examples of date parameter combinations are shown below.                Filtering by datetime:                    /balancing/dynamic/all?settlementDate=2023-01-18T01:00Z                Filtering by settlement date and period:                    /balancing/dynamic/all?settlementDate=2023-01-18&settlementPeriod=3  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.balancing_dynamic_all_get_with_http_info(settlement_date, settlement_period, bm_unit, dataset, format, async_req=True)
        >>> result = thread.get()

        :param settlement_date: The settlement date or datetime to filter. (required)
        :type settlement_date: datetime
        :param settlement_period: The settlement period to filter. This should be an integer from 1-50 inclusive.
        :type settlement_period: int
        :param bm_unit: The BM Units to query. Elexon or NGC BMU IDs can be used. If omitted, results for all BM units will be returned.
        :type bm_unit: List[str]
        :param dataset: Datasets to filter. If omitted, all datasets will be returned.
        :type dataset: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicDynamicData, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'settlement_date',
            'settlement_period',
            'bm_unit',
            'dataset',
            'format'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method balancing_dynamic_all_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('settlement_date') is not None:  # noqa: E501
            if isinstance(_params['settlement_date'], datetime):
                _query_params.append(('settlementDate', _params['settlement_date'].strftime(self.api_client.configuration.datetime_format)))
            else:
                _query_params.append(('settlementDate', _params['settlement_date']))

        if _params.get('settlement_period') is not None:  # noqa: E501
            _query_params.append(('settlementPeriod', _params['settlement_period']))

        if _params.get('bm_unit') is not None:  # noqa: E501
            _query_params.append(('bmUnit', _params['bm_unit']))
            _collection_formats['bmUnit'] = 'multi'

        if _params.get('dataset') is not None:  # noqa: E501
            _query_params.append(('dataset', _params['dataset']))
            _collection_formats['dataset'] = 'multi'

        if _params.get('format') is not None:  # noqa: E501
            _query_params.append(('format', _params['format']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json', 'application/xml', 'text/xml', 'text/csv'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicDynamicData",
            '400': None,
            '500': None,
        }

        return self.api_client.call_api(
            '/balancing/dynamic/all', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def balancing_dynamic_get(self, bm_unit : Annotated[StrictStr, Field(..., description="The BM Unit to query.")], snapshot_at : Annotated[datetime, Field(..., description="When to retrieve a snapshot of data at.  That is, the latest datapoint before this time will be returned for each dataset.")], until : Annotated[Optional[datetime], Field(description="When to retrieve data until.  Data from the snapshot until this time will be returned.")] = None, snapshot_at_settlement_period : Annotated[Optional[StrictInt], Field(description="The settlement period to retrieve a snapshot of data at.  If provided, the time part of SnapshotAt will be ignored.")] = None, until_settlement_period : Annotated[Optional[StrictInt], Field(description="The settlement period to retrieve data until.  If provided, the time part of Until will be ignored.")] = None, dataset : Annotated[Optional[conlist(StrictStr)], Field(description="Datasets to filter. If omitted, all datasets will be returned.")] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicDynamicData:  # noqa: E501
        """Dynamic Datasets Per-BMU  # noqa: E501

        This endpoint provides the dynamic data for a requested BMU, excluding physical rate data.  It returns a \"snapshot\" of data valid at a given time, and optionally a time series of changes over a requested interval.                By default, all of the relevant datasets are returned: SIL, SEL, NDZ, NTB, NTO, MZT, MNZT, MDV, MDP.  The results from each dataset are transformed to a common response model, with the common integer field *Value*  mapped from the fields *Level*, *Period*, *Volume* or *Notice* in the original dataset, as relevant.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.balancing_dynamic_get(bm_unit, snapshot_at, until, snapshot_at_settlement_period, until_settlement_period, dataset, format, async_req=True)
        >>> result = thread.get()

        :param bm_unit: The BM Unit to query. (required)
        :type bm_unit: str
        :param snapshot_at: When to retrieve a snapshot of data at.  That is, the latest datapoint before this time will be returned for each dataset. (required)
        :type snapshot_at: datetime
        :param until: When to retrieve data until.  Data from the snapshot until this time will be returned.
        :type until: datetime
        :param snapshot_at_settlement_period: The settlement period to retrieve a snapshot of data at.  If provided, the time part of SnapshotAt will be ignored.
        :type snapshot_at_settlement_period: int
        :param until_settlement_period: The settlement period to retrieve data until.  If provided, the time part of Until will be ignored.
        :type until_settlement_period: int
        :param dataset: Datasets to filter. If omitted, all datasets will be returned.
        :type dataset: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicDynamicData
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the balancing_dynamic_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.balancing_dynamic_get_with_http_info(bm_unit, snapshot_at, until, snapshot_at_settlement_period, until_settlement_period, dataset, format, **kwargs)  # noqa: E501

    @validate_arguments
    def balancing_dynamic_get_with_http_info(self, bm_unit : Annotated[StrictStr, Field(..., description="The BM Unit to query.")], snapshot_at : Annotated[datetime, Field(..., description="When to retrieve a snapshot of data at.  That is, the latest datapoint before this time will be returned for each dataset.")], until : Annotated[Optional[datetime], Field(description="When to retrieve data until.  Data from the snapshot until this time will be returned.")] = None, snapshot_at_settlement_period : Annotated[Optional[StrictInt], Field(description="The settlement period to retrieve a snapshot of data at.  If provided, the time part of SnapshotAt will be ignored.")] = None, until_settlement_period : Annotated[Optional[StrictInt], Field(description="The settlement period to retrieve data until.  If provided, the time part of Until will be ignored.")] = None, dataset : Annotated[Optional[conlist(StrictStr)], Field(description="Datasets to filter. If omitted, all datasets will be returned.")] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Dynamic Datasets Per-BMU  # noqa: E501

        This endpoint provides the dynamic data for a requested BMU, excluding physical rate data.  It returns a \"snapshot\" of data valid at a given time, and optionally a time series of changes over a requested interval.                By default, all of the relevant datasets are returned: SIL, SEL, NDZ, NTB, NTO, MZT, MNZT, MDV, MDP.  The results from each dataset are transformed to a common response model, with the common integer field *Value*  mapped from the fields *Level*, *Period*, *Volume* or *Notice* in the original dataset, as relevant.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.balancing_dynamic_get_with_http_info(bm_unit, snapshot_at, until, snapshot_at_settlement_period, until_settlement_period, dataset, format, async_req=True)
        >>> result = thread.get()

        :param bm_unit: The BM Unit to query. (required)
        :type bm_unit: str
        :param snapshot_at: When to retrieve a snapshot of data at.  That is, the latest datapoint before this time will be returned for each dataset. (required)
        :type snapshot_at: datetime
        :param until: When to retrieve data until.  Data from the snapshot until this time will be returned.
        :type until: datetime
        :param snapshot_at_settlement_period: The settlement period to retrieve a snapshot of data at.  If provided, the time part of SnapshotAt will be ignored.
        :type snapshot_at_settlement_period: int
        :param until_settlement_period: The settlement period to retrieve data until.  If provided, the time part of Until will be ignored.
        :type until_settlement_period: int
        :param dataset: Datasets to filter. If omitted, all datasets will be returned.
        :type dataset: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicDynamicData, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'bm_unit',
            'snapshot_at',
            'until',
            'snapshot_at_settlement_period',
            'until_settlement_period',
            'dataset',
            'format'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method balancing_dynamic_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('bm_unit') is not None:  # noqa: E501
            _query_params.append(('bmUnit', _params['bm_unit']))

        if _params.get('snapshot_at') is not None:  # noqa: E501
            if isinstance(_params['snapshot_at'], datetime):
                _query_params.append(('snapshotAt', _params['snapshot_at'].strftime(self.api_client.configuration.datetime_format)))
            else:
                _query_params.append(('snapshotAt', _params['snapshot_at']))

        if _params.get('until') is not None:  # noqa: E501
            if isinstance(_params['until'], datetime):
                _query_params.append(('until', _params['until'].strftime(self.api_client.configuration.datetime_format)))
            else:
                _query_params.append(('until', _params['until']))

        if _params.get('snapshot_at_settlement_period') is not None:  # noqa: E501
            _query_params.append(('snapshotAtSettlementPeriod', _params['snapshot_at_settlement_period']))

        if _params.get('until_settlement_period') is not None:  # noqa: E501
            _query_params.append(('untilSettlementPeriod', _params['until_settlement_period']))

        if _params.get('dataset') is not None:  # noqa: E501
            _query_params.append(('dataset', _params['dataset']))
            _collection_formats['dataset'] = 'multi'

        if _params.get('format') is not None:  # noqa: E501
            _query_params.append(('format', _params['format']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json', 'application/xml', 'text/xml', 'text/csv'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicDynamicData",
            '400': None,
            '500': None,
        }

        return self.api_client.call_api(
            '/balancing/dynamic', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def balancing_dynamic_rates_all_get(self, settlement_date : Annotated[datetime, Field(..., description="The settlement date or datetime to filter.")], settlement_period : Annotated[Optional[StrictInt], Field(description="The settlement period to filter. This should be an integer from 1-50 inclusive.")] = None, bm_unit : Annotated[Optional[conlist(StrictStr)], Field(description="The BM Units to query. Elexon or NGC BMU IDs can be used. If omitted, results for all BM units will be returned.")] = None, dataset : Annotated[Optional[conlist(StrictStr)], Field(description="Datasets to return. If omitted, all datasets will be returned.")] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicRateData:  # noqa: E501
        """Rate Datasets Market-Wide  # noqa: E501

        This endpoint provides market-wide physical rate data, for all BMUs or a requested set of multiple BMUs.  It returns the data valid for a given settlement period. This includes a snapshot of data valid at the start  of the settlement period, and any changes published during that settlement period.                The settlement period to query can be specified as a date and settlement period, or as a datetime  which will resolve to the settlement period that time falls within.    By default, all of the relevant datasets are returned: RDRE, RURE, RDRI, RURI.                All Dates and DateTimes should be expressed as defined within  <a href=\"https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\" target=\"_blank\">RFC 3339</a>.    Some examples of date parameter combinations are shown below.                Filtering by datetime:                    /balancing/dynamic/rates/all?settlementDate=2023-01-18T01:00Z                Filtering by settlement date and period:                    /balancing/dynamic/rates/all?settlementDate=2023-01-18&settlementPeriod=3  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.balancing_dynamic_rates_all_get(settlement_date, settlement_period, bm_unit, dataset, format, async_req=True)
        >>> result = thread.get()

        :param settlement_date: The settlement date or datetime to filter. (required)
        :type settlement_date: datetime
        :param settlement_period: The settlement period to filter. This should be an integer from 1-50 inclusive.
        :type settlement_period: int
        :param bm_unit: The BM Units to query. Elexon or NGC BMU IDs can be used. If omitted, results for all BM units will be returned.
        :type bm_unit: List[str]
        :param dataset: Datasets to return. If omitted, all datasets will be returned.
        :type dataset: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicRateData
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the balancing_dynamic_rates_all_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.balancing_dynamic_rates_all_get_with_http_info(settlement_date, settlement_period, bm_unit, dataset, format, **kwargs)  # noqa: E501

    @validate_arguments
    def balancing_dynamic_rates_all_get_with_http_info(self, settlement_date : Annotated[datetime, Field(..., description="The settlement date or datetime to filter.")], settlement_period : Annotated[Optional[StrictInt], Field(description="The settlement period to filter. This should be an integer from 1-50 inclusive.")] = None, bm_unit : Annotated[Optional[conlist(StrictStr)], Field(description="The BM Units to query. Elexon or NGC BMU IDs can be used. If omitted, results for all BM units will be returned.")] = None, dataset : Annotated[Optional[conlist(StrictStr)], Field(description="Datasets to return. If omitted, all datasets will be returned.")] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Rate Datasets Market-Wide  # noqa: E501

        This endpoint provides market-wide physical rate data, for all BMUs or a requested set of multiple BMUs.  It returns the data valid for a given settlement period. This includes a snapshot of data valid at the start  of the settlement period, and any changes published during that settlement period.                The settlement period to query can be specified as a date and settlement period, or as a datetime  which will resolve to the settlement period that time falls within.    By default, all of the relevant datasets are returned: RDRE, RURE, RDRI, RURI.                All Dates and DateTimes should be expressed as defined within  <a href=\"https://datatracker.ietf.org/doc/html/rfc3339#section-5.6\" target=\"_blank\">RFC 3339</a>.    Some examples of date parameter combinations are shown below.                Filtering by datetime:                    /balancing/dynamic/rates/all?settlementDate=2023-01-18T01:00Z                Filtering by settlement date and period:                    /balancing/dynamic/rates/all?settlementDate=2023-01-18&settlementPeriod=3  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.balancing_dynamic_rates_all_get_with_http_info(settlement_date, settlement_period, bm_unit, dataset, format, async_req=True)
        >>> result = thread.get()

        :param settlement_date: The settlement date or datetime to filter. (required)
        :type settlement_date: datetime
        :param settlement_period: The settlement period to filter. This should be an integer from 1-50 inclusive.
        :type settlement_period: int
        :param bm_unit: The BM Units to query. Elexon or NGC BMU IDs can be used. If omitted, results for all BM units will be returned.
        :type bm_unit: List[str]
        :param dataset: Datasets to return. If omitted, all datasets will be returned.
        :type dataset: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicRateData, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'settlement_date',
            'settlement_period',
            'bm_unit',
            'dataset',
            'format'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method balancing_dynamic_rates_all_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('settlement_date') is not None:  # noqa: E501
            if isinstance(_params['settlement_date'], datetime):
                _query_params.append(('settlementDate', _params['settlement_date'].strftime(self.api_client.configuration.datetime_format)))
            else:
                _query_params.append(('settlementDate', _params['settlement_date']))

        if _params.get('settlement_period') is not None:  # noqa: E501
            _query_params.append(('settlementPeriod', _params['settlement_period']))

        if _params.get('bm_unit') is not None:  # noqa: E501
            _query_params.append(('bmUnit', _params['bm_unit']))
            _collection_formats['bmUnit'] = 'multi'

        if _params.get('dataset') is not None:  # noqa: E501
            _query_params.append(('dataset', _params['dataset']))
            _collection_formats['dataset'] = 'multi'

        if _params.get('format') is not None:  # noqa: E501
            _query_params.append(('format', _params['format']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json', 'application/xml', 'text/xml', 'text/csv'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicRateData",
            '400': None,
            '500': None,
        }

        return self.api_client.call_api(
            '/balancing/dynamic/rates/all', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def balancing_dynamic_rates_get(self, bm_unit : Annotated[StrictStr, Field(..., description="The BM Unit to query.")], snapshot_at : Annotated[datetime, Field(..., description="When to retrieve a snapshot of data at.  That is, the latest datapoint before this time will be returned for each dataset.")], until : Annotated[Optional[datetime], Field(description="When to retrieve data until.  Data from the snapshot until this time will be returned.")] = None, snapshot_at_settlement_period : Annotated[Optional[StrictInt], Field(description="The settlement period to retrieve a snapshot of data at.  If provided, the time part of SnapshotAt will be ignored.")] = None, until_settlement_period : Annotated[Optional[StrictInt], Field(description="The settlement period to retrieve data until.  If provided, the time part of Until will be ignored.")] = None, dataset : Annotated[Optional[conlist(StrictStr)], Field(description="Datasets to filter. If empty, all datasets will be returned.")] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicRateData:  # noqa: E501
        """Rate Datasets Per-BMU  # noqa: E501

        This endpoint provides the physical rate data for a requested BMU.  It returns a \"snapshot\" of data valid at a given time, and optionally a time series of changes over a requested interval.                By default, all of the relevant datasets are returned: RDRE, RURE, RDRI, RURI.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.balancing_dynamic_rates_get(bm_unit, snapshot_at, until, snapshot_at_settlement_period, until_settlement_period, dataset, format, async_req=True)
        >>> result = thread.get()

        :param bm_unit: The BM Unit to query. (required)
        :type bm_unit: str
        :param snapshot_at: When to retrieve a snapshot of data at.  That is, the latest datapoint before this time will be returned for each dataset. (required)
        :type snapshot_at: datetime
        :param until: When to retrieve data until.  Data from the snapshot until this time will be returned.
        :type until: datetime
        :param snapshot_at_settlement_period: The settlement period to retrieve a snapshot of data at.  If provided, the time part of SnapshotAt will be ignored.
        :type snapshot_at_settlement_period: int
        :param until_settlement_period: The settlement period to retrieve data until.  If provided, the time part of Until will be ignored.
        :type until_settlement_period: int
        :param dataset: Datasets to filter. If empty, all datasets will be returned.
        :type dataset: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicRateData
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the balancing_dynamic_rates_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.balancing_dynamic_rates_get_with_http_info(bm_unit, snapshot_at, until, snapshot_at_settlement_period, until_settlement_period, dataset, format, **kwargs)  # noqa: E501

    @validate_arguments
    def balancing_dynamic_rates_get_with_http_info(self, bm_unit : Annotated[StrictStr, Field(..., description="The BM Unit to query.")], snapshot_at : Annotated[datetime, Field(..., description="When to retrieve a snapshot of data at.  That is, the latest datapoint before this time will be returned for each dataset.")], until : Annotated[Optional[datetime], Field(description="When to retrieve data until.  Data from the snapshot until this time will be returned.")] = None, snapshot_at_settlement_period : Annotated[Optional[StrictInt], Field(description="The settlement period to retrieve a snapshot of data at.  If provided, the time part of SnapshotAt will be ignored.")] = None, until_settlement_period : Annotated[Optional[StrictInt], Field(description="The settlement period to retrieve data until.  If provided, the time part of Until will be ignored.")] = None, dataset : Annotated[Optional[conlist(StrictStr)], Field(description="Datasets to filter. If empty, all datasets will be returned.")] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Rate Datasets Per-BMU  # noqa: E501

        This endpoint provides the physical rate data for a requested BMU.  It returns a \"snapshot\" of data valid at a given time, and optionally a time series of changes over a requested interval.                By default, all of the relevant datasets are returned: RDRE, RURE, RDRI, RURI.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.balancing_dynamic_rates_get_with_http_info(bm_unit, snapshot_at, until, snapshot_at_settlement_period, until_settlement_period, dataset, format, async_req=True)
        >>> result = thread.get()

        :param bm_unit: The BM Unit to query. (required)
        :type bm_unit: str
        :param snapshot_at: When to retrieve a snapshot of data at.  That is, the latest datapoint before this time will be returned for each dataset. (required)
        :type snapshot_at: datetime
        :param until: When to retrieve data until.  Data from the snapshot until this time will be returned.
        :type until: datetime
        :param snapshot_at_settlement_period: The settlement period to retrieve a snapshot of data at.  If provided, the time part of SnapshotAt will be ignored.
        :type snapshot_at_settlement_period: int
        :param until_settlement_period: The settlement period to retrieve data until.  If provided, the time part of Until will be ignored.
        :type until_settlement_period: int
        :param dataset: Datasets to filter. If empty, all datasets will be returned.
        :type dataset: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicRateData, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'bm_unit',
            'snapshot_at',
            'until',
            'snapshot_at_settlement_period',
            'until_settlement_period',
            'dataset',
            'format'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method balancing_dynamic_rates_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('bm_unit') is not None:  # noqa: E501
            _query_params.append(('bmUnit', _params['bm_unit']))

        if _params.get('snapshot_at') is not None:  # noqa: E501
            if isinstance(_params['snapshot_at'], datetime):
                _query_params.append(('snapshotAt', _params['snapshot_at'].strftime(self.api_client.configuration.datetime_format)))
            else:
                _query_params.append(('snapshotAt', _params['snapshot_at']))

        if _params.get('until') is not None:  # noqa: E501
            if isinstance(_params['until'], datetime):
                _query_params.append(('until', _params['until'].strftime(self.api_client.configuration.datetime_format)))
            else:
                _query_params.append(('until', _params['until']))

        if _params.get('snapshot_at_settlement_period') is not None:  # noqa: E501
            _query_params.append(('snapshotAtSettlementPeriod', _params['snapshot_at_settlement_period']))

        if _params.get('until_settlement_period') is not None:  # noqa: E501
            _query_params.append(('untilSettlementPeriod', _params['until_settlement_period']))

        if _params.get('dataset') is not None:  # noqa: E501
            _query_params.append(('dataset', _params['dataset']))
            _collection_formats['dataset'] = 'multi'

        if _params.get('format') is not None:  # noqa: E501
            _query_params.append(('format', _params['format']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json', 'application/xml', 'text/xml', 'text/csv'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesBalancingDynamicRateData",
            '400': None,
            '500': None,
        }

        return self.api_client.call_api(
            '/balancing/dynamic/rates', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
