# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError

from typing_extensions import Annotated
from datetime import date, datetime

from pydantic import Field, StrictBool, StrictInt, StrictStr, conlist

from typing import List, Optional

from openapi_client.models.insights_api_models_responses_generation_generation_by_fuel_type import InsightsApiModelsResponsesGenerationGenerationByFuelType
from openapi_client.models.insights_api_models_responses_generation_outturn_generation_by_settlement_period import InsightsApiModelsResponsesGenerationOutturnGenerationBySettlementPeriod
from openapi_client.models.insights_api_models_responses_response_with_metadata1_insights_api_models_responses_generation_half_hourly_interconnector_outturn import InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationHalfHourlyInterconnectorOutturn

from openapi_client.api_client import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class GenerationOutturnApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def generation_outturn_fuelinsthhcur_get(self, fuel_type : Optional[conlist(StrictStr)] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> List[InsightsApiModelsResponsesGenerationGenerationByFuelType]:  # noqa: E501
        """Generation by fuel type categories (FUELINSTHHCUR)  # noqa: E501

        This endpoint provides a snapshot view of the last 24 hours generation by individual fuel type categories including interconnector.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.generation_outturn_fuelinsthhcur_get(fuel_type, format, async_req=True)
        >>> result = thread.get()

        :param fuel_type:
        :type fuel_type: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[InsightsApiModelsResponsesGenerationGenerationByFuelType]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the generation_outturn_fuelinsthhcur_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.generation_outturn_fuelinsthhcur_get_with_http_info(fuel_type, format, **kwargs)  # noqa: E501

    @validate_arguments
    def generation_outturn_fuelinsthhcur_get_with_http_info(self, fuel_type : Optional[conlist(StrictStr)] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Generation by fuel type categories (FUELINSTHHCUR)  # noqa: E501

        This endpoint provides a snapshot view of the last 24 hours generation by individual fuel type categories including interconnector.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.generation_outturn_fuelinsthhcur_get_with_http_info(fuel_type, format, async_req=True)
        >>> result = thread.get()

        :param fuel_type:
        :type fuel_type: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[InsightsApiModelsResponsesGenerationGenerationByFuelType], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'fuel_type',
            'format'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method generation_outturn_fuelinsthhcur_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('fuel_type') is not None:  # noqa: E501
            _query_params.append(('fuelType', _params['fuel_type']))
            _collection_formats['fuelType'] = 'multi'

        if _params.get('format') is not None:  # noqa: E501
            _query_params.append(('format', _params['format']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json', 'application/xml', 'text/xml', 'text/csv'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "List[InsightsApiModelsResponsesGenerationGenerationByFuelType]",
        }

        return self.api_client.call_api(
            '/generation/outturn/FUELINSTHHCUR', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def generation_outturn_half_hourly_interconnector_get(self, publish_date_time_from : Optional[datetime] = None, publish_date_time_to : Optional[datetime] = None, settlement_date_from : Annotated[Optional[date], Field(description="The settlement date from filter. This must be in the format yyyy-MM-dd.")] = None, settlement_date_to : Annotated[Optional[date], Field(description="The settlement date to filter. This must be in the format yyyy-MM-dd.")] = None, settlement_period : Optional[conlist(StrictInt, unique_items=True)] = None, interconnector_name : Optional[conlist(StrictStr)] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationHalfHourlyInterconnectorOutturn:  # noqa: E501
        """Interconnector Flow  # noqa: E501

        This endpoint provides the interconnector flows report derived from the Generation by Fuel Type (FUELINST)  data and shows both interconnector imports and exports; the data is updated every five minutes.                Settlement date parameters must be provided in the exact format yyyy-MM-dd.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.generation_outturn_half_hourly_interconnector_get(publish_date_time_from, publish_date_time_to, settlement_date_from, settlement_date_to, settlement_period, interconnector_name, format, async_req=True)
        >>> result = thread.get()

        :param publish_date_time_from:
        :type publish_date_time_from: datetime
        :param publish_date_time_to:
        :type publish_date_time_to: datetime
        :param settlement_date_from: The settlement date from filter. This must be in the format yyyy-MM-dd.
        :type settlement_date_from: date
        :param settlement_date_to: The settlement date to filter. This must be in the format yyyy-MM-dd.
        :type settlement_date_to: date
        :param settlement_period:
        :type settlement_period: List[int]
        :param interconnector_name:
        :type interconnector_name: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationHalfHourlyInterconnectorOutturn
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the generation_outturn_half_hourly_interconnector_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.generation_outturn_half_hourly_interconnector_get_with_http_info(publish_date_time_from, publish_date_time_to, settlement_date_from, settlement_date_to, settlement_period, interconnector_name, format, **kwargs)  # noqa: E501

    @validate_arguments
    def generation_outturn_half_hourly_interconnector_get_with_http_info(self, publish_date_time_from : Optional[datetime] = None, publish_date_time_to : Optional[datetime] = None, settlement_date_from : Annotated[Optional[date], Field(description="The settlement date from filter. This must be in the format yyyy-MM-dd.")] = None, settlement_date_to : Annotated[Optional[date], Field(description="The settlement date to filter. This must be in the format yyyy-MM-dd.")] = None, settlement_period : Optional[conlist(StrictInt, unique_items=True)] = None, interconnector_name : Optional[conlist(StrictStr)] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Interconnector Flow  # noqa: E501

        This endpoint provides the interconnector flows report derived from the Generation by Fuel Type (FUELINST)  data and shows both interconnector imports and exports; the data is updated every five minutes.                Settlement date parameters must be provided in the exact format yyyy-MM-dd.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.generation_outturn_half_hourly_interconnector_get_with_http_info(publish_date_time_from, publish_date_time_to, settlement_date_from, settlement_date_to, settlement_period, interconnector_name, format, async_req=True)
        >>> result = thread.get()

        :param publish_date_time_from:
        :type publish_date_time_from: datetime
        :param publish_date_time_to:
        :type publish_date_time_to: datetime
        :param settlement_date_from: The settlement date from filter. This must be in the format yyyy-MM-dd.
        :type settlement_date_from: date
        :param settlement_date_to: The settlement date to filter. This must be in the format yyyy-MM-dd.
        :type settlement_date_to: date
        :param settlement_period:
        :type settlement_period: List[int]
        :param interconnector_name:
        :type interconnector_name: List[str]
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationHalfHourlyInterconnectorOutturn, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'publish_date_time_from',
            'publish_date_time_to',
            'settlement_date_from',
            'settlement_date_to',
            'settlement_period',
            'interconnector_name',
            'format'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method generation_outturn_half_hourly_interconnector_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('publish_date_time_from') is not None:  # noqa: E501
            if isinstance(_params['publish_date_time_from'], datetime):
                _query_params.append(('publishDateTimeFrom', _params['publish_date_time_from'].strftime(self.api_client.configuration.datetime_format)))
            else:
                _query_params.append(('publishDateTimeFrom', _params['publish_date_time_from']))

        if _params.get('publish_date_time_to') is not None:  # noqa: E501
            if isinstance(_params['publish_date_time_to'], datetime):
                _query_params.append(('publishDateTimeTo', _params['publish_date_time_to'].strftime(self.api_client.configuration.datetime_format)))
            else:
                _query_params.append(('publishDateTimeTo', _params['publish_date_time_to']))

        if _params.get('settlement_date_from') is not None:  # noqa: E501
            if isinstance(_params['settlement_date_from'], date):
                _query_params.append(('settlementDateFrom', _params['settlement_date_from'].strftime(self.api_client.configuration.date_format)))
            else:
                _query_params.append(('settlementDateFrom', _params['settlement_date_from']))

        if _params.get('settlement_date_to') is not None:  # noqa: E501
            if isinstance(_params['settlement_date_to'], date):
                _query_params.append(('settlementDateTo', _params['settlement_date_to'].strftime(self.api_client.configuration.date_format)))
            else:
                _query_params.append(('settlementDateTo', _params['settlement_date_to']))

        if _params.get('settlement_period') is not None:  # noqa: E501
            _query_params.append(('settlementPeriod', _params['settlement_period']))
            _collection_formats['settlementPeriod'] = 'multi'

        if _params.get('interconnector_name') is not None:  # noqa: E501
            _query_params.append(('interconnectorName', _params['interconnector_name']))
            _collection_formats['interconnectorName'] = 'multi'

        if _params.get('format') is not None:  # noqa: E501
            _query_params.append(('format', _params['format']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json', 'application/xml', 'text/xml', 'text/csv'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "InsightsApiModelsResponsesResponseWithMetadata1InsightsApiModelsResponsesGenerationHalfHourlyInterconnectorOutturn",
        }

        return self.api_client.call_api(
            '/generation/outturn/halfHourlyInterconnector', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def generation_outturn_summary_get(self, start_time : Optional[datetime] = None, end_time : Optional[datetime] = None, include_negative_generation : Optional[StrictBool] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> List[InsightsApiModelsResponsesGenerationOutturnGenerationBySettlementPeriod]:  # noqa: E501
        """Outturn Summary  # noqa: E501

        ⚠ This endpoint provides a down-sampled data summary intended for visualisation purposes.  Use raw dataset endpoints under /datasets for full access.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.generation_outturn_summary_get(start_time, end_time, include_negative_generation, format, async_req=True)
        >>> result = thread.get()

        :param start_time:
        :type start_time: datetime
        :param end_time:
        :type end_time: datetime
        :param include_negative_generation:
        :type include_negative_generation: bool
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[InsightsApiModelsResponsesGenerationOutturnGenerationBySettlementPeriod]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the generation_outturn_summary_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.generation_outturn_summary_get_with_http_info(start_time, end_time, include_negative_generation, format, **kwargs)  # noqa: E501

    @validate_arguments
    def generation_outturn_summary_get_with_http_info(self, start_time : Optional[datetime] = None, end_time : Optional[datetime] = None, include_negative_generation : Optional[StrictBool] = None, format : Annotated[Optional[StrictStr], Field(description="Response data format. Use json/xml to include metadata.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Outturn Summary  # noqa: E501

        ⚠ This endpoint provides a down-sampled data summary intended for visualisation purposes.  Use raw dataset endpoints under /datasets for full access.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.generation_outturn_summary_get_with_http_info(start_time, end_time, include_negative_generation, format, async_req=True)
        >>> result = thread.get()

        :param start_time:
        :type start_time: datetime
        :param end_time:
        :type end_time: datetime
        :param include_negative_generation:
        :type include_negative_generation: bool
        :param format: Response data format. Use json/xml to include metadata.
        :type format: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[InsightsApiModelsResponsesGenerationOutturnGenerationBySettlementPeriod], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'start_time',
            'end_time',
            'include_negative_generation',
            'format'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method generation_outturn_summary_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('start_time') is not None:  # noqa: E501
            if isinstance(_params['start_time'], datetime):
                _query_params.append(('startTime', _params['start_time'].strftime(self.api_client.configuration.datetime_format)))
            else:
                _query_params.append(('startTime', _params['start_time']))

        if _params.get('end_time') is not None:  # noqa: E501
            if isinstance(_params['end_time'], datetime):
                _query_params.append(('endTime', _params['end_time'].strftime(self.api_client.configuration.datetime_format)))
            else:
                _query_params.append(('endTime', _params['end_time']))

        if _params.get('include_negative_generation') is not None:  # noqa: E501
            _query_params.append(('includeNegativeGeneration', _params['include_negative_generation']))

        if _params.get('format') is not None:  # noqa: E501
            _query_params.append(('format', _params['format']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'application/xml'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "List[InsightsApiModelsResponsesGenerationOutturnGenerationBySettlementPeriod]",
        }

        return self.api_client.call_api(
            '/generation/outturn/summary', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
